### PR TITLE
Private dev

### PR DESCRIPTION
**Pull request by tmisawa**

### CODE REVIEW

**Comment by xrq-phys** [comment]
I would suggest moving StdFace submodule from `/src/StdFace/submodule` to `/src/StdFace`.

@tmisawa what do you think?
Btw it seems that the traditional makefile also needs fixing (which is easy).

**Comment by yomichi** [comment]
@xrq-phys 
I agree with your suggestion.

The `submodule` is a nice mechanism to include other projects, but this works only when `git clone`d although we sometimes want to use archive file to obtain sources.
This is why other ISSP's projects have such as `StdFace/submodule` and other directories to by-pass the `submodule` mechanism (eg. download or manual clone).

Today, I found a smart tool, [`git-archive-all`](https://github.com/Kentzo/git-archive-all). This can make an archive file that includes a copy of the `submodule`d repositories. I think that it is better to attach this archive file to the release page.

**Comment by xrq-phys** [comment]
@yomichi Sorry I didn't see the `/src/StdFace/CMakeList.txt` which clones StdFace to `/src/StdFace/clone`.

Yes! `git archive` does not support recursive behavior, which is quite annoying.

I'll wait until you finished deploying `git-archive-all` to, maybe, `dist.sh`?

I can then start working on fixing traditional makefile and merging #26 since my block-pfaffian branch is using submodules extensively.

Thanks!

**Comment by yomichi** [comment]
I just update `dist.sh` to use `git-archive-all`

**Comment by xrq-phys** [comment]
Excellent! I'll try moving `StdFace` and adjust `CMakeLists.txt` accordingly.

Thanks,

**Comment by xrq-phys** [comment]
I'm directly pushing the changes.

Please revert if any of you consider this inappropriate.

**Comment by xrq-phys** [comment]
Great job! Thanks!

and Sorry for the delay :D

**Comment by xrq-phys** [comment]
@tmisawa Added commit 2356343 (directly to `tree/develop` to address CI failure.

Will check also `mVMCconfig.sh` later.

**Comment by tmisawa** [comment]
@xrq-phys 
thank you!

**Pull request merged**
